version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/data:/app/data
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.prod
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: /api
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

# Placeholder for DB service if needed later, e.g., Postgres
# db:
#   image: postgres:13
#   volumes:
#     - postgres_data:/var/lib/postgresql/data/
#   environment:
#     - POSTGRES_DB=filehub
#     - POSTGRES_USER=user
#     - POSTGRES_PASSWORD=password 