# Generated by Django 4.2.20 on 2025-04-20 20:15

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file', models.FileField(upload_to=files.models.physical_file_upload_path)),
                ('size', models.BigIntegerField(editable=False)),
                ('content_type', models.CharField(editable=False, max_length=255)),
                ('extension', models.CharField(blank=True, editable=False, max_length=20)),
                ('first_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('physical_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logical_files', to='files.physicalfile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
