# Generated by Django 4.2.20 on 2025-04-20 12:41

from django.db import migrations, models
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=files.models.get_upload_path)),
                ('size', models.BigIntegerField(editable=False)),
                ('content_type', models.CharField(editable=False, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
